#!/usr/bin/env bash

main() {
	local black="\E[0;90m"
	local yellow="\E[0;93m"
	local red="\E[0;91m"
	local nocolor="\E[0m"

	local hostnames=( `ls /etc/lxc/*.conf | grep -v 'lxc.conf' | sed -e's/\/etc\/lxc\/\(.*\)\.conf/\1/'` )
	local running_hosts=( `ps ax | perl -ne '/.*lxc-start.*\-n\s([\w\d\-\._]+).*/ && print "$1\n"'` )
	local i=0

	declare -A hosts
	declare -A items

	for host in ${hostnames[@]}; do
		if [ `echo ${running_hosts[@]} | tr ' ' '\n' | grep -c "^${host}$"` -ge 1 ]; then
			local hwaddr=`cat /etc/lxc/${host}.conf | grep hwaddr | sed -e 's/lxc\.network\.hwaddr\ =\ \(.*\)/\1/' | tr '[A-Z]' '[a-z]'`
			local ip=`cat /var/lib/misc/dnsmasq*.leases  | grep "${hwaddr}" | cut -d ' ' -f 3`
			if [ ! -z "${hwaddr}" ] && [ ! -z "${ip}" ]; then
				hosts[${host}]=${ip}
				items[${i}]=${host}
				let i++
			fi
		fi
	done

	if [ ${i} -eq 0 ]; then
		echo -e "lxcssh: ${red}No running container found!${nocolor}"
		exit 1
	fi

	local options=()
	local dest_ip=

	for item in ${!items[@]}; do
		ip=${hosts[${items[${item}]}]}
		options+=("${yellow}[${item}] ${nocolor}${items[${item}]} ${black}(${ip})${nocolor}")
		if [ ! -z "${1}" ] && ([ "${1}" = "${item}" ] || [ "${1}" = "${items[${item}]}" ]); then
			dest_ip=${ip}
		fi
	done

	if [ -z "${dest_ip}" ]; then
		echo
		for o in ${!options[@]}; do
			echo -e "  ${options[${o}]}"
		done
		echo
		exit 1
	fi

	local login=`whoami`

	ssh -oStrictHostKeyChecking=no -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPreferredAuthentications=publickey \
	    -2 -i `getent passwd ${login} | cut -d: -f6`/.ssh/lxc_rsa -l ${login} ${dest_ip} "${*:2}"
}

main ${*}
